In [1]:
from pandas import DataFrame, Series
import pandas as pd
import numpy as np
import uuid
import sys
import pandas as pd
from datetime import date, timedelta
sys.path.append("../../")
from genesis.entities.EODData import EODData
from genesis.entities.CollectionEODData import CollectionEODData
from genesis.persistence.CollectionEODDataPersistence import CollectionEODDataPersistence
%load_ext autoreload
%autoreload 2

ModuleNotFoundError: No module named 'genesis'

In [20]:
df = DataFrame(
    [{
        "symbol": "AMZN", 
        "name": "SUPER PETRO", 
        "exchange": "NASDAQ"
    },{
        "symbol": "BBAS3", 
        "name": "SUPER PETRO", 
        "exchange": "NYSE"
    },
    ], 
    index=[0, 1]
)
df2 = DataFrame(
    [{
        "symbol": "AMZN", 
        "name": "SUPER PETRO", 
        "exchange": "NASDAQ"
    },{
        "symbol": "VALE3", 
        "name": "VAKE PETRO", 
        "exchange": "BOVESPA"
    },
    ], 
    index=[1, 2]
)

In [65]:
#df.set_index("exchange", inplace=True)

df_directly = pd.DataFrame(
    dict(
        ticker="AMZN",
        open = 10,
        high = 15,
        low = 5,
        close = 20,
        volume = 120,
        oi = 130,
        exchange="NASDAQ"
        )
    , 
    index=pd.Series([date.today() - timedelta(days=3)], name="date")
    
)

df_directly.index = pd.to_datetime(df_directly.index)
df_directly.index[-1].to_pydatetime().date()

datetime.date(2018, 7, 31)

In [73]:
from os import path

In [93]:
from genesis.entities.CollectionEODData import CollectionEODData
from genesis.persistence.CollectionEODDataPersistence import CollectionEODDataPersistence
from genesis.persistence.CollectionEODDataPersistence import CollectionEODDataPersistence
collection = CollectionEODDataPersistence.get(ticker="A",exchange="NYSE")

collection.to_df()

In [83]:
path_str = "D:\desenvolvimento\ls\genesis-backend\data\eoddata\A_NYSE.csv"
    
path.isfile(path_str)

False

In [85]:
    string_file = """
,date,open,high,low,close,volume,ticker
0,2011-07-13,25.0,25.0,24.97,24.97,4364.0,XMPT
1,2011-07-14,24.97,24.98,24.95,24.95,3800.0,XMPT
2,2011-07-15,24.95,24.95,24.829,24.829,300.0,XMPT
3,2011-07-18,25.39,25.39,24.67,24.67,2530.0,XMPT
4,2011-07-19,24.62,24.69,24.62,24.68,1168.0,XMPT
5,2011-07-20,24.75,24.75,24.74,24.75,1314.0,XMPT
6,2011-07-21,24.87,24.92,24.8615,24.89,7202.0,XMPT
7,2011-07-22,24.86,25.02,24.85,25.006,20830.0,XMPT
8,2011-07-25,25.0,25.0,24.87,24.92,8600.0,XMPT
9,2011-07-26,24.84,24.84,24.7,24.7,2500.0,XMPT
10,2011-07-27,24.85,24.85,24.26,24.26,4200.0,XMPT
11,2011-07-28,24.1199,24.31,24.1199,24.31,6500.0,XMPT
12,2011-07-29,24.14,24.15,24.08,24.1079,1025.0,XMPT
13,2011-08-01,24.5,24.58,24.5,24.58,9610.0,XMPT
14,2011-08-02,24.58,24.58,24.58,24.58,500.0,XMPT
15,2011-08-03,24.752,24.76,24.74,24.76,675.0,XMPT
16,2011-08-04,24.95,24.95,24.73,24.73,3900.0,XMPT
17,2011-08-05,24.62,24.63,24.2,24.4,2779.0,XMPT
18,2011-08-08,23.6,23.809,23.56,23.56,954.0,XMPT
19,2011-08-09,23.5,23.93,23.5,23.887,1900.0,XMPT
20,2011-08-10,24.14,24.14,24.14,24.14,100.0,XMPT
21,2011-08-11,24.5,24.5,24.33,24.4,2796.0,XMPT
22,2011-08-12,24.66,24.72,24.66,24.72,200.0,XMPT
23,2011-08-15,24.88,24.93,24.88,24.93,3402.0,XMPT
24,2011-08-16,25.03,25.03,24.93,24.97,1900.0,XMPT
25,2011-08-17,25.1,25.1,25.1,25.1,1000.0,XMPT
26,2011-08-18,25.05,25.05,24.8,24.88,700.0,XMPT
27,2011-08-22,25.0,25.0,25.0,25.0,150.0,XMPT
28,2011-08-23,26.2,26.2,25.13,25.13,1000.0,XMPT
29,2011-08-24,25.137,25.17,25.127,25.17,2900.0,XMPT
30,2011-08-25,25.16,25.16,25.09,25.09,3450.0,XMPT
31,2011-08-29,25.22,25.39,25.22,25.25,2099.0,XMPT
32,2011-08-30,25.34,25.34,25.34,25.34,1400.0,XMPT
33,2011-08-31,25.45,25.61,25.4499,25.48,5775.0,XMPT
34,2011-09-01,25.51,25.55,25.35,25.35,750.0,XMPT"""

In [95]:
import io
f = io.StringIO(string_file)
df = pd.read_csv(f)
f.close()
df.set_index("date", inplace=True)
df.reset_index()

          date  Unnamed: 0     open    high      low    close   volume ticker
0   2011-07-13           0  25.0000  25.000  24.9700  24.9700   4364.0   XMPT
1   2011-07-14           1  24.9700  24.980  24.9500  24.9500   3800.0   XMPT
2   2011-07-15           2  24.9500  24.950  24.8290  24.8290    300.0   XMPT
3   2011-07-18           3  25.3900  25.390  24.6700  24.6700   2530.0   XMPT
4   2011-07-19           4  24.6200  24.690  24.6200  24.6800   1168.0   XMPT
5   2011-07-20           5  24.7500  24.750  24.7400  24.7500   1314.0   XMPT
6   2011-07-21           6  24.8700  24.920  24.8615  24.8900   7202.0   XMPT
7   2011-07-22           7  24.8600  25.020  24.8500  25.0060  20830.0   XMPT
8   2011-07-25           8  25.0000  25.000  24.8700  24.9200   8600.0   XMPT
9   2011-07-26           9  24.8400  24.840  24.7000  24.7000   2500.0   XMPT
10  2011-07-27          10  24.8500  24.850  24.2600  24.2600   4200.0   XMPT
11  2011-07-28          11  24.1199  24.310  24.1199  24.3100   6500.0   XMPT
12  2011-07-29          12  24.1400  24.150  24.0800  24.1079   1025.0   XMPT
13  2011-08-01          13  24.5000  24.580  24.5000  24.5800   9610.0   XMPT
14  2011-08-02          14  24.5800  24.580  24.5800  24.5800    500.0   XMPT
15  2011-08-03          15  24.7520  24.760  24.7400  24.7600    675.0   XMPT
16  2011-08-04          16  24.9500  24.950  24.7300  24.7300   3900.0   XMPT
17  2011-08-05          17  24.6200  24.630  24.2000  24.4000   2779.0   XMPT
18  2011-08-08          18  23.6000  23.809  23.5600  23.5600    954.0   XMPT
19  2011-08-09          19  23.5000  23.930  23.5000  23.8870   1900.0   XMPT
20  2011-08-10          20  24.1400  24.140  24.1400  24.1400    100.0   XMPT
21  2011-08-11          21  24.5000  24.500  24.3300  24.4000   2796.0   XMPT
22  2011-08-12          22  24.6600  24.720  24.6600  24.7200    200.0   XMPT
23  2011-08-15          23  24.8800  24.930  24.8800  24.9300   3402.0   XMPT
24  2011-08-16          24  25.0300  25.030  24.9300  24.9700   1900.0   XMPT
25  2011-08-17          25  25.1000  25.100  25.1000  25.1000   1000.0   XMPT
26  2011-08-18          26  25.0500  25.050  24.8000  24.8800    700.0   XMPT
27  2011-08-22          27  25.0000  25.000  25.0000  25.0000    150.0   XMPT
28  2011-08-23          28  26.2000  26.200  25.1300  25.1300   1000.0   XMPT
29  2011-08-24          29  25.1370  25.170  25.1270  25.1700   2900.0   XMPT
30  2011-08-25          30  25.1600  25.160  25.0900  25.0900   3450.0   XMPT
31  2011-08-29          31  25.2200  25.390  25.2200  25.2500   2099.0   XMPT
32  2011-08-30          32  25.3400  25.340  25.3400  25.3400   1400.0   XMPT
33  2011-08-31          33  25.4500  25.610  25.4499  25.4800   5775.0   XMPT
34  2011-09-01          34  25.5100  25.550  25.3500  25.3500    750.0   XMPT